s = set()
n = input("Enter no 1: ")
s.add(int(n))
n = input("Enter no 1: ")
s.add(int(n))
n = input("Enter no 1: ")
s.add(int(n))
n = input("Enter no 1: ")
s.add(int(n))
n = input("Enter no 1: ")
s.add(int(n))
n = input("Enter no 1: ")
s.add(int(n))
n = input("Enter no 1: ")
s.add(int(n))
n = input("Enter no 1: ")
s.add(int(n))

print(s)